#include <stdint.h>
#include <stddef.h>

typedef struct dnafx_effect {
	uint8_t id;
	const char *name;
	uint8_t params;
	const char *param_names[6];
} dnafx_effect;

dnafx_effect dnafx_effect_fx_comp[] = {
	{ .id = 0, .name = "CRY WAH", .params = 4,
		.param_names = { [0] = "Q", [1] = "POSITION", [2] = "PEAK", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
	{ .id = 1, .name = "535 WAH", .params = 4,
		.param_names = { [0] = "Q", [1] = "POSITION", [2] = "PEAK", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
	{ .id = 2, .name = "AUTO WAH", .params = 4,
		.param_names = { [0] = "RATE", [1] = "RANGE", [2] = "PEAK", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
	{ .id = 3, .name = "TALK WAH AH", .params = 4,
		.param_names = { [0] = "RATE", [1] = "RANGE", [2] = "PEAK", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
	{ .id = 4, .name = "TOUCH WAH", .params = 4,
		.param_names = { [0] = "RATE", [1] = "RANGE", [2] = "PEAK", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
	{ .id = 5, .name = "TOUCH WAH ENVELOPE", .params = 4,
		.param_names = { [0] = "ATTACK", [1] = "SENS", [2] = "PEAK", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
	{ .id = 6, .name = "YELLOW COMP", .params = 4,
		.param_names = { [0] = "ATTACK", [1] = "THRES", [2] = "RATIO", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
	{ .id = 7, .name = "BLUE COMP", .params = 4,
		.param_names = { [0] = "ATTACK", [1] = "THRES", [2] = "RATIO", [3] = "LEVEL", [4] = NULL, [5] = NULL }},
};

dnafx_effect dnafx_effect_ds_od[] = {
	{ .id = 0, .name = "TUBE DR", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 1, .name = "808", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 2, .name = "PURE BOOST", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 3, .name = "FLEX BOOST", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 4, .name = "DDRIVE", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 5, .name = "BLACKRAT", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 6, .name = "GREY FAZE", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 7, .name = "MUFFY", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 8, .name = "MTL ZONE", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 9, .name = "MTL MASTER", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 10, .name = "OBSESSIVE DIST", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 11, .name = "JIMMY OD", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 12, .name = "FULL DRV", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 13, .name = "SHRED", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 14, .name = "BeeBee PRE", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 15, .name = "BeeBee +", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 16, .name = "RIET", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 17, .name = "TIGHT DS", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 18, .name = "FULL DS", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 19, .name = "GOLD CLON", .params = 3,
		.param_names = { [0] = "VOLUME", [1] = "TONE", [2] = "GAIN", [3] = NULL, [4] = NULL, [5] = NULL }},
};

dnafx_effect dnafx_effect_amp[] = {
	{ .id = 0, .name = "65US DX", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 1, .name = "65 USTW", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 2, .name = "59 US BASS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 3, .name = "US SONIC", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 4, .name = "US BLUES CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 5, .name = "US BLUES OD", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 6, .name = "J800", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 7, .name = "J900", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 8, .name = "PLX 100", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 9, .name = "E650 CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 10, .name = "E650 DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 11, .name = "POWERBELL CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 12, .name = "POWERBELL DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 13, .name = "BLACKNIGHT CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 14, .name = "BLACKNIGHT DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 15, .name = "MARKIII CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 16, .name = "MARKIII DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 17, .name = "MARKV CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 18, .name = "MARKV DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 19, .name = "TRI REC CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 20, .name = "TRI REC DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 21, .name = "ROCK VRB CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 22, .name = "ROCK VRB DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 23, .name = "CITRUS 30", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 24, .name = "CITRUS 50", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 25, .name = "SLOW 100 CR", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 26, .name = "SLOW 100 DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 27, .name = "DR.ZEE 18 JR", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 28, .name = "DR.ZEE", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 29, .name = "JET100H CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 30, .name = "JET100H OD", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 31, .name = "JAZZ 120", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 32, .name = "UK30 CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 33, .name = "UK30 DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 34, .name = "HWT103", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 35, .name = "Pv5050 CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 36, .name = "Pv5050 DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 37, .name = "REGAL TONE CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 38, .name = "REGAL TONE Od1", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 39, .name = "REGAL TONE Od2", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 40, .name = "CAROL CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 41, .name = "CAROL DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 42, .name = "CARDEEF", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 43, .name = "Ev5050 CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 44, .name = "Ev5050 DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 45, .name = "HT CLUB CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 46, .name = "HT CLUB DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 47, .name = "HUGEN CL", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 48, .name = "HUGEN OD", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 49, .name = "HUGEN DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 50, .name = "KOCHE OD", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 51, .name = "KOCHE DS", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 52, .name = "ACOUSTIC 1", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 53, .name = "ACOUSTIC 2", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
	{ .id = 54, .name = "ACOUSTIC 3", .params = 6,
		.param_names = { [0] = "GAIN", [1] = "BASS", [2] = "MID", [3] = "TREBLE", [4] = "PRES", [5] = "MST" }},
};

dnafx_effect dnafx_effect_cab[] = {
	{ .id = 0, .name = "US DLX112", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 1, .name = "US TWN 212", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 2, .name = "US BASS 410", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 3, .name = "SONIC 112", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 4, .name = "BLUES 112", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 5, .name = "1960 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 6, .name = "EAGLE P412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 7, .name = "EAGLE S412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 8, .name = "MARK 112", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 9, .name = "REC 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 10, .name = "CITRUS 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 11, .name = "CITRUS 212", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 12, .name = "SLOW 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 13, .name = "DRZEE 112", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 14, .name = "DRZEE 212", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 15, .name = "JAZZ 212", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 16, .name = "UK 212", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 17, .name = "HW T412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 18, .name = "PV 5050 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 19, .name = "REGAL TONE 110", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 20, .name = "TWO STONES 212", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 21, .name = "CARDEFF 112", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 22, .name = "EV 5050 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 23, .name = "HT 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 24, .name = "GAS STATION 412", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 25, .name = "ACOUSTIC 112", .params = 4,
		.param_names = { [0] = "TUBE", [1] = "MIC", [2] = "CENTER", [3] = "DISTANCE", [4] = NULL, [5] = NULL }},
	{ .id = 26, .name = "Custom IR 1", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 27, .name = "Custom IR 2", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 28, .name = "Custom IR 3", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 29, .name = "Custom IR 4", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 30, .name = "Custom IR 5", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 31, .name = "Custom IR 6", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 32, .name = "Custom IR 7", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 33, .name = "Custom IR 8", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 34, .name = "Custom IR 9", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 35, .name = "Custom IR 10", .params = 1,
		.param_names = { [0] = "TUBE", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
};

dnafx_effect dnafx_effect_ns_gate[] = {
	{ .id = 0, .name = "NOISE KILLER", .params = 1,
		.param_names = { [0] = "THRES", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 1, .name = "INTEL REDUCER", .params = 1,
		.param_names = { [0] = "SENS", [1] = NULL, [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 2, .name = "NOISE GATE", .params = 3,
		.param_names = { [0] = "ATTACK", [1] = "RELEASE", [2] = "THRES", [3] = NULL, [4] = NULL, [5] = NULL }},
};

dnafx_effect dnafx_effect_eq[] = {
	{ .id = 0, .name = "GUITAR EQ", .params = 5,
		.param_names = { [0] = "100Hz", [1] = "250Hz", [2] = "630Hz", [3] = "1.6KHz", [4] = "4KHz", [5] = NULL }},
	{ .id = 1, .name = "METAL EQ", .params = 5,
		.param_names = { [0] = "80Hz", [1] = "240Hz", [2] = "750Hz", [3] = "2.2KHz", [4] = "6.6KHz", [5] = NULL }},
	{ .id = 2, .name = "6BAND EQ", .params = 6,
		.param_names = { [0] = "100Hz", [1] = "200Hz", [2] = "400Hz", [3] = "800Hz", [4] = "1.6KHz", [5] = "3.2KHz" }},
	{ .id = 3, .name = "CUSTOM EQ", .params = 6,
		.param_names = { [0] = "GAIN1", [1] = "100Hz", [2] = "GAIN2", [3] = "600Hz", [4] = "GAIN3", [5] = "1250Hz" }},
};

dnafx_effect dnafx_effect_mod[] = {
	{ .id = 0, .name = "PHASER", .params = 3,
		.param_names = { [0] = "RATE", [1] = "LEVEL", [2] = "DEPTH", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 1, .name = "STEP PHASER", .params = 3,
		.param_names = { [0] = "RATE", [1] = "LEVEL", [2] = "DEPTH", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 2, .name = "FAT PHASER", .params = 3,
		.param_names = { [0] = "RATE", [1] = "LEVEL", [2] = "DEPTH", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 3, .name = "FLANGER", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "F.BACK", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 4, .name = "JET-FLANGER", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "F.BACK", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 5, .name = "TREMOLO", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "TONE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 6, .name = "STUTTER", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "TONE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 7, .name = "VIBRATO", .params = 3,
		.param_names = { [0] = "RATE", [1] = "DEPTH", [2] = "TONE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 8, .name = "PITCH SHIFT", .params = 3,
		.param_names = { [0] = "PITCH", [1] = "MIX", [2] = "TONE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 9, .name = "DETUNE", .params = 3,
		.param_names = { [0] = "PITCH", [1] = "MIX", [2] = "TONE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 10, .name = "ROTARY", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "TONE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 11, .name = "ANA-CHORUS", .params = 4,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "TONE", [3] = "DEPTH", [4] = NULL, [5] = NULL }},
	{ .id = 12, .name = "TRI-CHORUS", .params = 4,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "TONE", [3] = "DEPTH", [4] = NULL, [5] = NULL }},
	{ .id = 13, .name = "RING MOD", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "TONE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 14, .name = "Q-FILTER", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "Q", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 15, .name = "HIGH PASS", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "RANGE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 16, .name = "LOW PASS", .params = 3,
		.param_names = { [0] = "RATE", [1] = "MIX", [2] = "RANGE", [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 17, .name = "SLOW GEAR", .params = 2,
		.param_names = { [0] = "RISE", [1] = "LEVEL", [2] = NULL, [3] = NULL, [4] = NULL, [5] = NULL }},
	{ .id = 18, .name = "LOFI", .params = 3,
		.param_names = { [0] = "SAMPLE", [1] = "MIX", [2] = "BIT", [3] = NULL, [4] = NULL, [5] = NULL }},
};

dnafx_effect dnafx_effect_delay[] = {
	{ .id = 0, .name = "DIGITAL", .params = 4,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = NULL, [5] = NULL }},
	{ .id = 1, .name = "ANALOG", .params = 4,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = NULL, [5] = NULL }},
	{ .id = 2, .name = "DYNAMIC", .params = 4,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = NULL, [5] = NULL }},
	{ .id = 3, .name = "REAL", .params = 4,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = NULL, [5] = NULL }},
	{ .id = 4, .name = "TAPE", .params = 4,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = NULL, [5] = NULL }},
	{ .id = 5, .name = "MOD", .params = 4,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = NULL, [5] = NULL }},
	{ .id = 6, .name = "REVERSE", .params = 4,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = NULL, [5] = NULL }},
	{ .id = 7, .name = "DUAL DELAY 2", .params = 5,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME", [3] = "SUB-D", [4] = "THRES", [5] = NULL }},
	{ .id = 8, .name = "PINGPONG", .params = 6,
		.param_names = { [0] = "LEVEL", [1] = "F.BACK", [2] = "TIME A", [3] = "SUB A", [4] = "TIME B", [5] = "SUB B" }},
};

dnafx_effect dnafx_effect_reverb[] = {
	{ .id = 0, .name = "ROOM", .params = 4,
		.param_names = { [0] = "P.DELAY", [1] = "LEVEL", [2] = "DECAY", [3] = "TONE", [4] = NULL, [5] = NULL }},
	{ .id = 1, .name = "HALL", .params = 4,
		.param_names = { [0] = "P.DELAY", [1] = "LEVEL", [2] = "DECAY", [3] = "TONE", [4] = NULL, [5] = NULL }},
	{ .id = 2, .name = "CHURCH", .params = 4,
		.param_names = { [0] = "P.DELAY", [1] = "LEVEL", [2] = "DECAY", [3] = "TONE", [4] = NULL, [5] = NULL }},
	{ .id = 3, .name = "PLATE", .params = 4,
		.param_names = { [0] = "P.DELAY", [1] = "LEVEL", [2] = "DECAY", [3] = "TONE", [4] = NULL, [5] = NULL }},
	{ .id = 4, .name = "SPRING", .params = 4,
		.param_names = { [0] = "P.DELAY", [1] = "LEVEL", [2] = "DECAY", [3] = "TONE", [4] = NULL, [5] = NULL }},
	{ .id = 5, .name = "MOD", .params = 4,
		.param_names = { [0] = "P.DELAY", [1] = "LEVEL", [2] = "DECAY", [3] = "TONE", [4] = NULL, [5] = NULL }},
	{ .id = 6, .name = "CAVE", .params = 4,
		.param_names = { [0] = "P.DELAY", [1] = "LEVEL", [2] = "DECAY", [3] = "TONE", [4] = NULL, [5] = NULL }},
};

typedef struct dnafx_section {
	uint8_t id;
	const char *name;
	uint8_t size;
	uint8_t max_params;
	uint8_t effects_max;
	dnafx_effect *effects;
} dnafx_section;

dnafx_section dnafx_sections[] = {
	{ .id = 0, .name = "FX/COMP", .size = 12, .max_params = 4,
		.effects_max = 7, .effects = &dnafx_effect_fx_comp[0] },
	{ .id = 1, .name = "DS/OD", .size = 10, .max_params = 3,
		.effects_max = 19, .effects = &dnafx_effect_ds_od[0] },
	{ .id = 2, .name = "AMP", .size = 16, .max_params = 6,
		.effects_max = 54, .effects = &dnafx_effect_amp[0] },
	{ .id = 3, .name = "CAB", .size = 14, .max_params = 5,
		.effects_max = 35, .effects = &dnafx_effect_cab[0] },
	{ .id = 4, .name = "NS GATE", .size = 10, .max_params = 3,
		.effects_max = 2, .effects = &dnafx_effect_ns_gate[0] },
	{ .id = 5, .name = "EQ", .size = 22, .max_params = 6,
		.effects_max = 4, .effects = &dnafx_effect_eq[0] },
	{ .id = 6, .name = "MOD", .size = 18, .max_params = 4,
		.effects_max = 18, .effects = &dnafx_effect_mod[0] },
	{ .id = 7, .name = "DELAY", .size = 18, .max_params = 5,
		.effects_max = 8, .effects = &dnafx_effect_delay[0] },
	{ .id = 8, .name = "REVERB", .size = 12, .max_params = 4,
		.effects_max = 6, .effects = &dnafx_effect_reverb[0] },
};

const char *dnafx_expression[] = {
	"MODULE_CTRL",
	"PARA_CTRL",
	"FUN_SWITCH",
	"VOL_SWITCH",
	"VOL_MIN",
	"VOL_MAX"
};
